### ISSUE TITLE
Google Maps come back inside activities

### ISSUE THREAD

**Issue by thomaschampagne** [thomaschampagne/stravistix#117]
Source issue: #116 from @ceinmart

>Hi Thomas , 

>How you probably already notice , strava not use google maps anymore.
This is terrible for a lot of users (include me) and all them are complain about this at strava forum . 
Check here : https://strava.zendesk.com/entries/95423147-Feedback-for-Strava-s-new-maps-Open-Street-Maps-

>I don't believe strava will back with google maps soon . 
So, can you enable a "patch" to use google maps instead the OSM ??
If you able to do that... you will gain a lot of users... and probably more $$ donators... 

>Thank you 
>Cesar

----
#### Details

Display result displayed in native Strava Map (mapbox + openstreetmap) with Google Map. User has to click on a button near native map to get popup which include same result with Google Maps as background.

#### Tasks
- [x] Main button **View in Google Maps** over native main MapBox. 
- [x] Display activity path inside Google Maps when  **View in Google Maps** main  button clicked
- [x] Display segment path inside Google Maps when  **View in Google Maps**  main button clicked (user has previously clicked a segment in segment list of his activity)
- [x] Button **View in Google Maps** inside segment area of an activity page  (user has previously clicked a segment in segment list of his activity)
- [x] Handle case when user click analysis then Overview
- [x] Ensure upper tasks works for running
- [x] Handle no activity maps, ex: https://www.strava.com/activities/324919571
- [x] Add new setting: Enable Google Maps support on Activity pages.

**Comment by thomaschampagne** [comment]
Think with:
http://www.jacquet80.eu/blog/post/2011/02/Display-GPX-tracks-using-Google-Maps-API

**Comment by jibees** [comment]
Hi there.
When I see the issue #116 , I see the two maps, but I want to be sure that you will not delete the OSM map ;) Sometimes, I do prefer OSM, especially for mountain biking. 
Thanks a lot !

**Comment by thomaschampagne** [comment]
Hi,

It will be released "as a option". Option is "you can use both maps." No OSM replacement. I like and use OSM maps for MTB singletracks too.

Don't worry ;)

Tom

**Comment by jibees** [comment]
Thanks a lot Thomas, and congrats for your great work.

jb
