### ISSUE TITLE
Swimming in fitness trend

### ISSUE THREAD

**Issue by thomaschampagne** [thomaschampagne/stravistix#327]
# Swim FTP calculation methods

## 1st method - 60 minutes swimming

Swim FTP (meters/min) = distance (m) / 60

## 2nd method - 30 minutes swimming

Swim FTP (meters/min) = (_distance(m)_ / 30)  - ( (2 * _distance(m)_ / 30 ) * 0.025)

## 3th method -  200m swim test, rest & swim 400m test

Swim FTP (meters/min) = (400m – 200m) / (_400mTimeInMinutes_ - _200mTimeInMinutes_)

# Swim Stress Score calculation method:

Normalized_Swim_Speed (m/min) = distance(m) / timeInMinutesNoRest

Intensity = Normalized_Swim_Speed / Swim FTP

Swim Stress Score  = Intensity^3  * TotalTimeInHours * 100

# Swim Stream sample:

```json
{"time":[0,23,45,67,90,114,136,158,182,204,226,252,274,298,313,329,348,367,379,551,583,608,629,660,691,725,763,794,816,846,870,890,910,1124,1154,1179,1204,1231,1255,1284,1308,1337,1359,1386,1411,1435,1460,1478,1552,1583,1607,1630,1682,1734,1787,1813,1840,1866,1894,1910,1987,2012,2036,2056,2066,2077,2104,2124,2145,2159,2168,2195,2218,2238,2250,2257,2284,2306,2327,2339,2348,2378,2396,2417,2432,2439,2466,2486,2509,2524,2527,2554,2574,2595,2608,2843,2871,2893,2915,2937,2958,2980,3004,3026,3050,3068,3092,3115,3139,3165,3188,3210,3232,3253,3273,3294,3318,3340,3362,3383,3407,3425,3557,3584,3604,3625,3638,3657,3683,3705,3727,3741,3757,3785,3807,3827,3840,3857,3884,3904,3926,3941,3957,3983,4005,4027,4040,4057,4085,4105,4127,4141,4157,4183,4205,4224,4238,4360,4481],"distance":[0.0,22.9,45.7,68.6,91.4,114.3,137.2,160.0,182.9,205.7,228.6,251.5,274.3,297.2,320.0,342.9,365.8,388.6,411.5,434.3,445.8,457.2,480.1,502.9,525.8,548.6,571.5,594.4,617.2,640.1,662.9,685.8,708.7,731.5,743.0,754.4,777.2,800.1,823.0,845.8,868.7,891.5,914.4,937.3,960.1,983.0,1005.8,1028.7,1051.6,1063.0,1074.4,1097.3,1120.1,1143.0,1165.9,1188.7,1211.6,1234.4,1257.3,1280.2,1303.0,1314.5,1325.9,1348.7,1371.6,1394.5,1405.9,1417.3,1440.2,1463.0,1485.9,1497.3,1508.8,1531.6,1554.5,1577.3,1588.8,1600.2,1623.1,1645.9,1668.8,1680.2,1691.6,1714.5,1737.4,1760.2,1771.7,1783.1,1805.9,1828.8,1851.7,1863.1,1874.5,1897.4,1920.2,1943.1,1954.5,1966.0,1988.8,2011.7,2034.5,2057.4,2080.3,2103.1,2126.0,2148.8,2171.7,2194.6,2217.4,2240.3,2263.1,2286.0,2308.9,2331.7,2354.6,2377.4,2400.3,2423.2,2446.0,2468.9,2491.7,2514.6,2537.5,2548.9,2560.3,2583.2,2606.0,2628.9,2640.3,2651.8,2674.6,2697.5,2720.3,2731.8,2743.2,2766.1,2788.9,2811.8,2823.2,2834.6,2857.5,2880.4,2903.2,2914.7,2926.1,2948.9,2971.8,2994.7,3006.1,3017.5,3040.4,3063.2,3086.1,3097.5,3109.0,3131.8,3154.7,3177.5,3177.5],"cadence":[0,26,24,22,21,21,23,22,21,20,23,23,24,21,20,19,16,26,22,20,20,31,25,29,23,30,24,19,28,24,31,25,31,45,45,29,30,28,26,28,26,26,25,26,27,26,26,27,27,27,27,27,27,28,26,28,29,26,24,25,22,22,28,26,24,23,23,26,26,25,24,24,25,25,25,23,23,25,26,26,22,22,25,26,25,24,24,25,26,23,23,23,29,25,26,23,23,25,25,27,28,26,27,27,27,27,28,30,25,23,27,30,28,27,28,30,28,27,27,27,31,31,23,23,27,28,28,24,24,32,29,27,24,24,32,29,27,24,24,32,26,27,27,27,32,29,27,24,24,32,30,27,24,24,30,31,28,27,27],"grade_adjusted_distance":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"resting":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]}
```
![image](https://cloud.githubusercontent.com/assets/151973/22244044/3e18bfae-e22a-11e6-9c32-e274279919bb.png)

# Source infos
## From bulk
Using activity.distance & activity.moving_time_raw 

- [x] Get fit/gpx file from a pool & free swim activities to check

Compute "Normalized_Swim_Speed (m/min)" (Swiming pool case) => OK
Compute "Normalized_Swim_Speed (m/min)" (Free swin Lake/Sea) => OK

### Swiming pool case (eg: https://www.strava.com/activities/433700361)
```javascript
this.pageView.activity().get('poolLength') = 33.33
this.pageView.activity().get('speedUnit') = "mp100m"
this.pageView.activity().get('average_speed') = 3312.99 (m/h)
```
> 1 / (3312.99m / 60min) * 100m = 1.811 min/100m = 108.6s/100m = 1:48min / 100m (pace match)

>  3312.99m / 60min = 55.2 m/min

Compute "Normalized_Swim_Speed (m/min)" => OK

### Lake/Sea cases (eg: https://www.strava.com/activities/842275942)

From lat/lon stream only?
Compute "Normalized_Swim_Speed (m/min)" => ?

# Tasks
- [ ] Compute total distance. From lon/lat? From pool lenght * distance.lenght ?
- [ ] Total time no rest. With "moving_time_raw" attr?
- [ ] Swim FTP field in athlete settings
- [ ] material icon: https://material.io/icons/#ic_pool
-
```
{"id":652212776,"type":"Swim","adjusting_elevation":false,"map_start_index":0,"bikes":[{"id":2042105,"name":"Aeroad CF SLX"},{"id":824309,"name":"Canyon Nerve AM 7"},{"id":2179055,"name":"Columbus"},{"id":1493775,"name":"Misc"},{"id":824321,"name":"RR"}],"shoes":[{"id":1022094,"name":"Kalenji","distance":40343},{"id":382540,"name":"adidas Blanc/Orange","distance":27131}],"startDateLocal":1469379889,"trainer":true,"use_timer_time":false,"speedUnit":"mp100m","showSegments":false,"showMap":false,"average_speed":920.3007518796992,"poolLength":17,"unitSystem":"metric","supportsGap":false}
```

**Comment by thomaschampagne** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/thomaschampagne/stravistix/issues/327](https://trello.com/c/cDpgtQHY/9-https-github-com-thomaschampagne-stravistix-issues-327)
