### ISSUE TITLE
Running stride length + Cycling crank revolution distance

### ISSUE THREAD

**Issue by thomaschampagne** [thomaschampagne/stravistix#443]
from: https://twitter.com/Crazie_Daizee/status/900739357979668485

# Todos:
- [ ] Add a "NEW" on each new stats label

**Running:**
- [x] Total steps
- [x] Avg stride length
- [x] 25% Stride Length
- [x] 50% Stride Length
- [x] 75% Stride Length

**Cycling:**
- [x] Avg Distance / Crank Revolution
- [x] 25% Distance / Crank Revolution
- [x] 50% Distance / Crank Revolution
- [x] 75% Distance / Crank Revolution

**Comment by philipwhiuk** [comment]
See also #25 #26
